services:
    seed:
        build:
            context: .
        ports:
            - "20000:20000"

    others:
        depends_on:
            -   seed
        build:
            context: .
        environment:
            - SEED_NODE=seed
        ports:
            - "30000:20000"

networks:
    default:
        driver: bridge